Repository Joelit0/Chatbot_Proyect, pull requests merged in 2022-07, with the labels that each got.

#29 Timer feature
  src/Library/Timer.cs
  src/Program/Program.cs
Labels: CR Requested

#33 Bot
  src/Library/ChainOfResponsibility/GameHandler.cs
  src/Library/ChainOfResponsibility/HelpHandler.cs
  src/Library/ChainOfResponsibility/MatchmakingHandler.cs
  src/Library/Game.cs
  src/Library/GamesList.cs
  src/Library/TelegramBot.cs
  src/Library/User.cs
  src/Program/Program.cs
Labels: CR Requested

#34 Improvement
  src/Library/ChainOfResponsibility/BaseHandler.cs
  src/Library/ChainOfResponsibility/GameHandler.cs
  src/Library/ChainOfResponsibility/GameVsIAHandler.cs
  src/Library/ChainOfResponsibility/MatchmakingHandler.cs
  src/Library/Game.cs
  src/Library/GameVsIA.cs
  src/Library/GamesList.cs
  src/Library/GamesVsIAList.cs
  src/Program/Program.cs
Labels: CR Requested

#38 Bot 2.0
  src/Library/Board.cs
  src/Library/ChainOfResponsibility/ChangeProfileInfoHandler.cs
  src/Library/ChainOfResponsibility/GameHandler.cs
  src/Library/ChainOfResponsibility/GameVsIAHandler.cs
  src/Library/ChainOfResponsibility/MatchmakingHandler.cs
  src/Library/ChainOfResponsibility/ProfileHandler.cs
  src/Library/ChainOfResponsibility/RegisterHandler.cs
  src/Library/Game.cs
  src/Library/GameVsIA.cs
  src/Library/GamesVsIAList.cs
  src/Library/KeywordsList.cs
  src/Library/User.cs
  src/Program/Program.cs
  src/Test/Library.Test/GameTest.cs
  src/Test/Library.Test/GamesListTest.cs
  src/Test/Library.Test/GamesVsIAListTest.cs
Labels: In Progress

#40 Nuevos tests para GameVsIA Handler
  src/Test/Library.Test/GameVsIAHandlerTest.cs
Labels: CR Requested

#41 Comments for some classes
  src/Library/ChainOfResponsibility/GameVsIAHandler.cs
  src/Library/Game.cs
  src/Library/GameVsIA.cs
  src/Library/GamesList.cs
  src/Library/GamesVsIAList.cs
Labels: CR Changes Requested
