Repository Joelit0/Chatbot_Proyect, pull requests merged in 2022-06, with the labels that each got.

#14 Board & Ship Logic
  src/Library/Board.cs
  src/Library/Ship.cs
  src/Library/Timer.cs
  src/Program/Program.cs
Labels: Approved

#18 Create tests for board class
  src/Library/Board.cs
  src/Test/Library.Test/BoardTest.cs
  src/Test/Library.Test/ShipTest.cs
  src/Test/Library.Test/UnitTest1.cs
Labels: CR Requested

#16 Create game class
  README.md
  src/Library/Game.cs
  src/Program/Program.cs
Labels: In Progress

#21 Comments and changes
  docs/UML.drawio
  src/Library/Board.cs
  src/Library/Ship.cs
  src/Library/Timer.cs
  src/Test/Library.Test/ShipTest.cs
  src/Test/Library.Test/ShipTests.cs
  src/Test/Library.Test/TimerTests.cs
Labels: CR Requested
